#!/usr/bin/env bash
#aliiii
domain=$1
subdomain=$2
sub=( www lb-01 web-01 web-02 )
if [[ $subdomain == "" ]]
then
    for x in "${sub[@]}"
        do
            echo "The subdomain $x is a $(dig $x.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}') record and points to $(dig $x.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
        done
     else
         echo "The subdomain $subdomain is a $(dig $subdomain.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}') record and points to $(dig $subdomain.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
     fi
ali () {
return 0
}
