#!/usr/bin/env bash
# InstallNginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
sudo /etc/init.d/nginx start
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
