#!/usr/bin/env bash
#
i=0

touch /var/run/myscript.pid
echo $BASHPID >> myscript.pid

trap "sudo rm -f /var/run/myscript.pid; echo I hate the kill command; exit" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm -f /var/run/myscript.pid; exit" SIGQUIT
while [ $i == 0 ]
do
	echo "To infinity and beyond"
	sleep 2

done
