#!/usr/bin/env bash
#read and cut
while IFS=: read -r a b c d e f j
do
	echo "The user $a is part of the $d gang, lives in $f and rides $j. $c's place is protected by the passcode $b, more info about the user here: $e"
done < "/etc/passwd"
