#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
hour=0
echo "Hour: $hour"
while [ $hour -le 12 ]
do
	echo "$counter"
	if [ $counter = 59 ]
	then
		counter=0
		((hour++))
		if [ $hour != 13 ]
		then
			echo "Hour: $hour"
		fi
	fi
	((counter++))
done
