#!/usr/bin/env bash
#to file or not to file
t=0
if test -e "school"
then
	echo "school file exists"
	((t = 1))
else
	echo "school file does not exist"
fi
if [ $t = 1 ]
then
	if test -s "school"
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if test -f "school"
	then
		echo "school is a regular file"
	fi
fi
