#!/usr/bin/env bash
#installing ufw
apt-get install ufw -y
#block all incoming traffic
sudo ufw default deny incoming
#open required ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
